version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
